### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by roma-guru** [killbill/killbill-qiwi-plugin#1]
I'm new to Ruby, so I may be doing something wrong:

``` sh
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » rvm use
Using /home/roma/.rvm/gems/jruby-1.7.20
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » rm -f Gemfile.lock Jarfile.lock .jbundler/classpath.rb
```

Clean, now bundle:

``` sh
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/..
Resolving dependencies........................
Using rake 11.1.2
Using i18n 0.6.11
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using rack 1.5.5
Using nokogiri 1.6.7.2
Using arel 5.0.1.20140414130214
Using jdbc-mysql 5.1.38
Using jdbc-sqlite3 3.8.11.2
Using diff-lcs 1.1.3
Using ffi 1.9.10
Using maven-tools 0.32.5
Using thor 0.19.1
Using jruby-openssl 0.9.16
Using tilt 1.4.1
Using rspec-core 2.12.2
Using rspec-mocks 2.12.2
Using bundler 1.11.2
Using money 6.1.1
Using tzinfo 1.1.0
Using rack-test 0.6.3
Using rack-protection 1.5.3
Using rspec-expectations 2.12.1
Using ethon 0.8.1
Using ruby-maven 3.0.4.1.4
Using monetize 0.3.0
Using activesupport 4.1.15
Using sinatra 1.3.6
Using rspec 2.12.0
Using typhoeus 0.6.9
Using jbundler 0.4.3
Using actionview 4.1.15
Using active_utils 2.2.3
Using activemodel 4.1.15
Using killbill 3.1.12
Using actionpack 4.1.15
Using activemerchant 1.42.9
Using activerecord 4.1.15
Using activerecord-jdbc-adapter 1.3.20
Using activerecord-jdbcmysql-adapter 1.3.20
Using activerecord-jdbcsqlite3-adapter 1.3.20
Using killbill-qiwi 0.0.1 from source at `.`
Bundle complete! 5 Gemfile dependencies, 45 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

``` sh
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » jbundle install
JBundler classpath:
  * /home/roma/.m2/repository/org/kill-bill/billing/killbill-api/0.9.5/killbill-api-0.9.5.jar
  * /home/roma/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.2/jackson-annotations-2.3.2.jar
  * /home/roma/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar
  * /home/roma/.m2/repository/org/kill-bill/billing/plugin/killbill-plugin-api-notification/0.7.2/killbill-plugin-api-notification-0.7.2.jar
  * /home/roma/.m2/repository/org/kill-bill/billing/plugin/killbill-plugin-api-payment/0.7.2/killbill-plugin-api-payment-0.7.2.jar
  * /home/roma/.m2/repository/org/kill-bill/billing/plugin/killbill-plugin-api-currency/0.7.2/killbill-plugin-api-currency-0.7.2.jar
  * /home/roma/.m2/repository/org/kill-bill/billing/killbill-util/0.11.2/killbill-util-0.11.2-tests.jar
  * /home/roma/.m2/repository/com/codahale/metrics/metrics-core/3.0.2/metrics-core-3.0.2.jar
  * /home/roma/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.jar
  * /home/roma/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.jar
  * /home/roma/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.3.2/jackson-dataformat-csv-2.3.2.jar
  * /home/roma/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.3.2/jackson-datatype-joda-2.3.2.jar
  * /home/roma/.m2/repository/com/jolbox/bonecp/0.8.0-rc3/bonecp-0.8.0-rc3.jar
  * /home/roma/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
  * /home/roma/.m2/repository/com/mchange/c3p0/0.9.2/c3p0-0.9.2.jar
  * /home/roma/.m2/repository/com/mchange/mchange-commons-java/0.2.3.3/mchange-commons-java-0.2.3.3.jar
  * /home/roma/.m2/repository/com/samskivert/jmustache/1.5/jmustache-1.5.jar
  * /home/roma/.m2/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar
  * /home/roma/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar
  * /home/roma/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
  * /home/roma/.m2/repository/org/apache/commons/commons-email/1.2/commons-email-1.2.jar
  * /home/roma/.m2/repository/javax/mail/mail/1.4.1/mail-1.4.1.jar
  * /home/roma/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
  * /home/roma/.m2/repository/org/apache/shiro/shiro-core/1.2.2/shiro-core-1.2.2.jar
  * /home/roma/.m2/repository/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar
  * /home/roma/.m2/repository/org/apache/shiro/shiro-ehcache/1.2.2/shiro-ehcache-1.2.2.jar
  * /home/roma/.m2/repository/org/apache/shiro/shiro-guice/1.2.2/shiro-guice-1.2.2.jar
  * /home/roma/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar
  * /home/roma/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
  * /home/roma/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
  * /home/roma/.m2/repository/com/google/inject/extensions/guice-multibindings/3.0/guice-multibindings-3.0.jar
  * /home/roma/.m2/repository/org/jdbi/jdbi/2.53/jdbi-2.53.jar
  * /home/roma/.m2/repository/com/google/code/findbugs/annotations/2.0.2/annotations-2.0.2.jar
  * /home/roma/.m2/repository/org/joda/joda-money/0.9/joda-money-0.9.jar
  * /home/roma/.m2/repository/org/kill-bill/billing/killbill-internal-api/0.11.2/killbill-internal-api-0.11.2.jar
  * /home/roma/.m2/repository/org/kill-bill/commons/killbill-clock/0.2.15/killbill-clock-0.2.15.jar
  * /home/roma/.m2/repository/org/kill-bill/commons/killbill-embeddeddb-common/0.2.15/killbill-embeddeddb-common-0.2.15.jar
  * /home/roma/.m2/repository/org/kill-bill/commons/killbill-locker/0.2.15/killbill-locker-0.2.15.jar
  * /home/roma/.m2/repository/com/h2database/h2/1.3.175/h2-1.3.175.jar
  * /home/roma/.m2/repository/org/kill-bill/commons/killbill-queue/0.2.15/killbill-queue-0.2.15.jar
  * /home/roma/.m2/repository/org/kill-bill/commons/killbill-jdbi/0.2.15/killbill-jdbi-0.2.15.jar
  * /home/roma/.m2/repository/org/skife/config/config-magic/0.14/config-magic-0.14.jar
  * /home/roma/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar
  * /home/roma/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar
  * /home/roma/.m2/repository/org/weakref/jmxutils/1.12/jmxutils-1.12.jar
  * /home/roma/.m2/repository/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar
  * /home/roma/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.54/bcpkix-jdk15on-1.54.jar
  * /home/roma/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar
Your jbundle is complete! Use `jbundle show` to see where the bundled jars are installed.
```

Then trying rake:

``` sh
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » bundle exec rake killbill:clean                                                           1 ↵
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rm -r pkg
rm -rf /home/roma/Projects/Github/KillBill/killbill-qiwi-plugin/killbill-qiwi
```

``` sh
roma-desktop :: Github/KillBill/killbill-qiwi-plugin ‹master*› » bundle exec rake build
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
killbill-qiwi 0.0.1 built to pkg/killbill-qiwi-0.0.1.gem.
```

``` sh
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Resolving dependencies.....
/home/roma/Projects/Github/KillBill/killbill-qiwi-plugin/killbill-qiwi/0.0.1/gems
W, [2016-04-15T23:58:55.574000 #8769]  WARN -- : Unable to stage i18n (0.6.11) from /home/roma/.rvm/gems/jruby-9.0.5.0/cache/i18n-0.6.11.gem: undefined method `pos' for #<Pathname:0x4beabeec>
rake aborted!
NoMethodError: undefined method `pos' for #<Pathname:0x4beabeec>
/home/roma/.rvm/gems/jruby-9.0.5.0/gems/killbill-3.1.12/lib/killbill/rake_task.rb:224:in `do_install_gem'
/home/roma/.rvm/gems/jruby-9.0.5.0/gems/killbill-3.1.12/lib/killbill/rake_task.rb:218:in `block in stage_dependencies'
/home/roma/.rvm/gems/jruby-9.0.5.0/gems/killbill-3.1.12/lib/killbill/rake_task.rb:209:in `stage_dependencies'
/home/roma/.rvm/gems/jruby-9.0.5.0/gems/killbill-3.1.12/lib/killbill/rake_task.rb:83:in `block in install'
/home/roma/.rvm/gems/jruby-9.0.5.0/bin/jruby_executable_hooks:15:in `<top>'
Tasks: TOP => killbill:package => killbill:stage
(See full trace by running task with --trace)
```

I have no clues where i18n is involved here...

**Comment by roma-guru** [comment]
I've taken these steps from here: http://docs.killbill.io/0.16/payment_plugin.html
And I've got the same result on jruby-9.0.5.0.

**Comment by pierre** [comment]
It looks like the code hasn't been updated for Kill Bill 0.16.x yet. I'll make the necessary changes.

**Comment by roma-guru** [comment]
Thank you very much, Pierre!

**Comment by pierre** [comment]
@roman-voropaev I've just pushed a fix. Could you pull and follow the steps again from http://docs.killbill.io/0.16/payment_plugin.html#_build?

Unfortunately, I don't have access to a QIWI account at the moment so I couldn't test the full flow. Let me know if you have any issue and we can iterate here.

**Comment by roma-guru** [comment]
Hooray! It builds! Thanks again.
I will test the plugin with a QIWI account in a few days.
